# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TodayWorkout' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  # Pods for TodayWorkout
  pod 'XMLCoder', '~> 0.14.0'
  pod 'Alamofire', '~> 5.5'

  target 'TodayWorkoutTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TodayWorkoutUITests' do
    # Pods for testing
  end

end
